#! /usr/bin/env bash
#
# Run minimal tests to ensure that the JSON AST of semgrep-core can be read
# back correctly by a Python program.
#
# Use the SEMGREP_CORE environment variable to set the path to semgrep-core
# if necessary.
#
set -eu

semgrep_core="semgrep-core"

if [[ -n "${SEMGREP_CORE+z}" ]]; then
  semgrep_core="$SEMGREP_CORE"
fi

echo "semgrep-core is: $(which semgrep-core)"
for javafile in data/*.java; do
  echo "### Dump JSON AST, read it from Python program: $javafile"
  "$semgrep_core" -lang java -generate_ast_json "$javafile"
  python3 read-ast.py < "$javafile".ast.json
done
